name: py38
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - ca-certificates=2023.11.17=hbcca054_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py38h578d9bd_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - openssl=3.0.12=h7f8727e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=py38h06a4308_0
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - prompt_toolkit=3.0.41=hd8ed1ab_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.0=pyhd8ed1ab_0
  - python=3.8.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyzmq=25.1.0=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.13.0=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.8
      - anyio==4.3.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - bitarray==2.8.1
      - boto3==1.34.103
      - botocore==1.34.103
      - cachetools==5.3.3
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - cmake==3.27.5
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.2
      - datasets==3.0.1
      - dill==0.3.8
      - dnspython==2.6.1
      - docker==7.0.0
      - email-validator==2.1.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.1
      - fairseq==0.12.2
      - fastapi==0.111.0
      - fastapi-cli==0.0.3
      - ffmpy==0.3.2
      - filelock==3.12.4
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2023.9.1
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gradio==4.31.0
      - gradio-client==0.16.2
      - grpcio==1.62.2
      - h11==0.14.0
      - hanlp==2.1.0b50
      - hanlp-common==0.0.19
      - hanlp-downloader==0.0.25
      - hanlp-restful==0.0.23
      - hanlp-trie==0.0.5
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - hydra-core==1.0.7
      - idna==3.4
      - importlib-metadata==6.11.0
      - importlib-resources==6.1.0
      - jieba==0.42.1
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.4.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - laser-encoders==0.0.2
      - lit==16.0.6
      - lxml==4.9.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.0.6
      - opencc==1.1.6
      - opencc-python-reimplemented==0.1.7
      - openpyxl==3.1.2
      - orjson==3.10.3
      - packaging==23.1
      - pandas==2.0.3
      - pathos==0.3.2
      - phrasetree==0.0.8
      - pillow==10.3.0
      - pkgutil-resolve-name==1.3.10
      - portalocker==2.8.2
      - pox==0.3.4
      - ppft==1.7.6.8
      - propcache==0.2.0
      - protobuf==4.25.3
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pybind11==2.11.1
      - pycparser==2.21
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydub==0.25.1
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2023.8.8
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - ruff==0.4.4
      - s3transfer==0.10.1
      - sacrebleu==2.3.1
      - sacremoses==0.1.0
      - safetensors==0.3.3
      - sagemaker==2.219.0
      - sastrawi==1.0.1
      - schema==0.7.7
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - smdebug-rulesconfig==1.0.1
      - sniffio==1.3.1
      - starlette==0.37.2
      - sympy==1.12
      - tabulate==0.9.0
      - tblib==3.0.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.3.0
      - threadpoolctl==3.5.0
      - tokenizers==0.11.6
      - tomlkit==0.12.0
      - toolz==0.12.1
      - toposort==1.5
      - torch==2.0.1
      - torchaudio==2.0.2
      - tqdm==4.66.5
      - transformers==4.33.2
      - triton==2.0.0
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2023.3
      - ujson==5.9.0
      - unicategories==0.1.2
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - websockets==11.0.3
      - werkzeug==3.0.2
      - xxhash==3.5.0
      - yarl==1.15.2
      - zipp==3.17.0
prefix: /home/mi2s/.conda/envs/py38
